dist: trusty
sudo: required
shallow_clone: true
services:
  - docker
language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
install:
  - cd "$TRAVIS_BUILD_DIR"
  - npm install
  - cd "$TRAVIS_BUILD_DIR/deploy"
  - npm install
script:
  - cd "$TRAVIS_BUILD_DIR"
  - npm run build
deploy:
  provider: script
  script: cd "$TRAVIS_BUILD_DIR/deploy" && npm run "deploy:travis-ci"
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false

# Web Interface settings:

## Disable "Build pushed pull requests"

## Environment Variables:
#### COHERENT_DOCKER_SETTINGS: '{ "host":"example.org:1234", "ca":"", "cert":"", "key":"" }'
#### COHERENT_APP_SETTINGS: '{ "env":"Staging", "settings":{ /* contents of appsettings.json */ } }'
