dist: trusty
sudo: required
language: node_js
node_js:
  - node
branches:
  except:
  - gh-pages
notifications:
  email: false

services:
  - docker
install:
  - cd scripts && npm ci && cd ..
  - npm ci

cache:
  directories:
    - node_modules
    - scripts/node_modules

script:
  - export repo_name=$(echo $TRAVIS_REPO_SLUG | cut -d"/" -f2)
  - npm run build -- --prod $([ "$TRAVIS_BRANCH" = 'master' ] && echo -- --base-href=/${repo_name}/)
  - docker build --tag webapp-coherent .

deploy:
  - provider: script
    skip_cleanup: true
    script: node scripts/deploy Production
    on:
      branch: master
  - provider: pages
    local-dir: dist/browser/
    skip-cleanup: true
    github-token:
      secure: myCU8EQjsLM8bulbjI5fk2APpYKJmUqXfGO0kao+NUmOyhHEy/ggFYvl3iaFaesSVU2AjfNdo0efyTbysiO7i62+QgPhzcyHs8Kn8EHFfyybVS8XOQDlpGXjo4zGcVTBbprhP4zZ6SxYb98waNlCTz+7zJkoMDTRnRk4CCeMtjvHDe+H1tB0W80fQyCd4ZzDgQMx9n5WAKWa72ZKlg73Kme9GX/bRHFJdlYJ/CScpahR1i70XbfuUX3IlKxn+EF8bQuovV8NrxWkrlykCg+6jdI1d8G5+Y6sbHi5LwWln23qaRxJQDtV2laQ7MuENlzNNnwIbxPacJ/u2N96o4SfQkP01HhVu4dBEjAfs3OzknvISjnLcpCMazJHGokK7JI9xMVC5ypoOni05Vhy+CxWgTOtvSk7ugSjZB1c+ZQjuA5eDaMjPzSPlAKQc88Gm/GJI/fhFuIvX3CQbxSb9A1nnZpDp+NH54wcr6wwbm+FAkOiBRRdkCoTTMkP2HlqX0OHgsFgZC4kNAcXqvRaKuL1a8UaeenRoYr2gk9//JDde6Yfyuu1/ZX4y5TJd9Khk2hwDNv5p3NsZcRiNTTT7whuczjU2x70n/ESPv12p2TuAr15LBVCtNUZbAJ/MS7x7ew5rNINesQYhdhvhA0t1aLL0/tSDpentPnf/zmXkTW+w3g=
    keep-history: true
    on:
      branch: master

env:
  # DEPLOY_SETTINGS_JSON='{"Production":[
  #   {"type":"docker","options":{"source":"webapp-coherent","target":"zevere/webapp-coherent","user":"","pass":""}},
  #   {"type":"heroku","options":{"app":"zevere","source":"zevere/webapp-coherent","dyno":"web","user":"","token":""}}
  # ]}'
  - secure: RmE07phyDhBL5R4G4g/+uvUS7vy4bPX6UWKPDSvp6lWN7ieublcK6g8R6wWnLd1ZVNuCpD/XgY3aGjAdIR4uvyQRpvvwv3BvkYJ8IWZ63Up6W6/8EAjvGd2rLf02gsCHj5wBr6xzZZ0H7ymN1lpdvCiIoUu713Ds9bEG9pgnhfase0b/UxEv5id5zOLY1W0yLrCVbFq8vd/2fynts7hB9IOoJdA/ehCgCl92BFboPAh/LhOyjiMFlTAKfWPj4eCP7Pv6YWXzyTBxH5k2g08aL1RAsMerGfE1Uhfcg2ZnwSPNaOI8uShI63OSpnYN6VvZLGTDYMsSXzd6JPkvaibncfIWbNy3A4+hZEcJFh+0v7dKiKkrXmA8/oM2wEw6K9urZimDO0Q3RfAdi3LC49VzQxlYH+2fw8BfAql+K6QmURyHc5UHXT9coHrmKyrLMnlkYabFqaxfmPHGDNmhtiE6MJ5j15HWA6Sd48APyMvMbIeEbxhtky6Gue7HQtx0iV0NTx9mspCLtp/MMnR5rNuSFfuym9QvvAsOpHbxhUfgoAAa9HypRjcSlxUSHOPIZUmGmsfVGDWKKzjFSn7t12oQHb55GZHCgy1qkniw2YgGtruhvfMEztgXzda/zPckXx5wlLha2BcmV95FMbujYjPuOt/5j7Rmhg+LZkTJvsEl7Hs=


# Disable "Build pushed pull requests"
